version: '3.1'
services:
  stats-server:
    build: ./stat-service
    image: stat-service-image
    container_name: stat-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstat
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=ewmstat

  ewm-service:
    build: ./ewm-service
    image: ewm-service-image
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - STAT_SERVER_PATH=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmapp
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewmapp
